[package]
name = "hamming-dict"
version = "0.1.0"
edition = "2018"

[features]
alloc = []

[dependencies]
bitarray = { version = "0.5.1", default-features = false }
rand = { version = "0.8.4", default-features = false }
rand_xoshiro = { version = "0.6.0", default-features = false }
